Traceback (most recent call last):
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2/cs5210594/infer.py", line 194, in <module>
    label_col = data[i]['table']['cols'][col_idx]
IndexError: list index out of range
Traceback (most recent call last):
  File "/scratch/cse/dual/cs5190443/col772-2302/A2_eval/COL772-2302-A2/evaluate_submission.py", line 12, in <module>
    sub_file = [json.loads(x) for x in open(submission_file)]
FileNotFoundError: [Errno 2] No such file or directory: 'cs5210594/predictions_new.jsonl'
